apiVersion: apps/v1
kind: Deployment
metadata:
    name: riskoptimizer-api
    labels:
        app: riskoptimizer-api
        component: backend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: riskoptimizer-api
    template:
        metadata:
            labels:
                app: riskoptimizer-api
        spec:
            containers:
                - name: api
                  image: riskoptimizer/backend:latest
                  ports:
                      - containerPort: 8000
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: riskoptimizer-secrets
                                key: database-url
                      - name: REDIS_URL
                        value: 'redis://riskoptimizer-redis:6379/0'
                      - name: CELERY_RESULT_BACKEND
                        value: 'redis://riskoptimizer-redis:6379/1'
                      - name: ENVIRONMENT
                        value: 'production'
                  resources:
                      requests:
                          memory: '512Mi'
                          cpu: '250m'
                      limits:
                          memory: '1Gi'
                          cpu: '500m'
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8000
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 8000
                      initialDelaySeconds: 5
                      periodSeconds: 5
                  volumeMounts:
                      - name: logs
                        mountPath: /app/logs
                      - name: tmp
                        mountPath: /app/tmp
            volumes:
                - name: logs
                  persistentVolumeClaim:
                      claimName: riskoptimizer-logs-pvc
                - name: tmp
                  emptyDir: {}
            imagePullSecrets:
                - name: riskoptimizer-registry-secret

---
apiVersion: v1
kind: Service
metadata:
    name: riskoptimizer-api-service
    labels:
        app: riskoptimizer-api
spec:
    selector:
        app: riskoptimizer-api
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8000
    type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: riskoptimizer-worker
    labels:
        app: riskoptimizer-worker
        component: backend
spec:
    replicas: 4
    selector:
        matchLabels:
            app: riskoptimizer-worker
    template:
        metadata:
            labels:
                app: riskoptimizer-worker
        spec:
            containers:
                - name: worker
                  image: riskoptimizer/backend:latest
                  command:
                      [
                          'celery',
                          '-A',
                          'tasks.celery_app',
                          'worker',
                          '--loglevel=info',
                          '--concurrency=2',
                      ]
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: riskoptimizer-secrets
                                key: database-url
                      - name: REDIS_URL
                        value: 'redis://riskoptimizer-redis:6379/0'
                      - name: CELERY_RESULT_BACKEND
                        value: 'redis://riskoptimizer-redis:6379/1'
                      - name: ENVIRONMENT
                        value: 'production'
                  resources:
                      requests:
                          memory: '1Gi'
                          cpu: '500m'
                      limits:
                          memory: '2Gi'
                          cpu: '1000m'
                  volumeMounts:
                      - name: logs
                        mountPath: /app/logs
                      - name: tmp
                        mountPath: /app/tmp
            volumes:
                - name: logs
                  persistentVolumeClaim:
                      claimName: riskoptimizer-logs-pvc
                - name: tmp
                  emptyDir: {}
            imagePullSecrets:
                - name: riskoptimizer-registry-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: riskoptimizer-beat
    labels:
        app: riskoptimizer-beat
        component: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: riskoptimizer-beat
    template:
        metadata:
            labels:
                app: riskoptimizer-beat
        spec:
            containers:
                - name: beat
                  image: riskoptimizer/backend:latest
                  command: ['celery', '-A', 'tasks.celery_app', 'beat', '--loglevel=info']
                  env:
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: riskoptimizer-secrets
                                key: database-url
                      - name: REDIS_URL
                        value: 'redis://riskoptimizer-redis:6379/0'
                      - name: CELERY_RESULT_BACKEND
                        value: 'redis://riskoptimizer-redis:6379/1'
                      - name: ENVIRONMENT
                        value: 'production'
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '100m'
                      limits:
                          memory: '512Mi'
                          cpu: '200m'
                  volumeMounts:
                      - name: logs
                        mountPath: /app/logs
            volumes:
                - name: logs
                  persistentVolumeClaim:
                      claimName: riskoptimizer-logs-pvc
            imagePullSecrets:
                - name: riskoptimizer-registry-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: riskoptimizer-redis
    labels:
        app: riskoptimizer-redis
        component: cache
spec:
    replicas: 1
    selector:
        matchLabels:
            app: riskoptimizer-redis
    template:
        metadata:
            labels:
                app: riskoptimizer-redis
        spec:
            containers:
                - name: redis
                  image: redis:7-alpine
                  ports:
                      - containerPort: 6379
                  command: ['redis-server', '--appendonly', 'yes']
                  resources:
                      requests:
                          memory: '256Mi'
                          cpu: '100m'
                      limits:
                          memory: '512Mi'
                          cpu: '200m'
                  volumeMounts:
                      - name: redis-data
                        mountPath: /data
                  livenessProbe:
                      exec:
                          command:
                              - redis-cli
                              - ping
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - redis-cli
                              - ping
                      initialDelaySeconds: 5
                      periodSeconds: 5
            volumes:
                - name: redis-data
                  persistentVolumeClaim:
                      claimName: riskoptimizer-redis-pvc

---
apiVersion: v1
kind: Service
metadata:
    name: riskoptimizer-redis
    labels:
        app: riskoptimizer-redis
spec:
    selector:
        app: riskoptimizer-redis
    ports:
        - protocol: TCP
          port: 6379
          targetPort: 6379
    type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: riskoptimizer-postgres
    labels:
        app: riskoptimizer-postgres
        component: database
spec:
    serviceName: riskoptimizer-postgres
    replicas: 1
    selector:
        matchLabels:
            app: riskoptimizer-postgres
    template:
        metadata:
            labels:
                app: riskoptimizer-postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15-alpine
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_DB
                        value: 'riskoptimizer'
                      - name: POSTGRES_USER
                        value: 'riskoptimizer'
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: riskoptimizer-secrets
                                key: postgres-password
                      - name: PGDATA
                        value: /var/lib/postgresql/data/pgdata
                  resources:
                      requests:
                          memory: '512Mi'
                          cpu: '250m'
                      limits:
                          memory: '1Gi'
                          cpu: '500m'
                  volumeMounts:
                      - name: postgres-data
                        mountPath: /var/lib/postgresql/data
                  livenessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - riskoptimizer
                      initialDelaySeconds: 30
                      periodSeconds: 10
                  readinessProbe:
                      exec:
                          command:
                              - pg_isready
                              - -U
                              - riskoptimizer
                      initialDelaySeconds: 5
                      periodSeconds: 5
    volumeClaimTemplates:
        - metadata:
              name: postgres-data
          spec:
              accessModes: ['ReadWriteOnce']
              resources:
                  requests:
                      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
    name: riskoptimizer-postgres
    labels:
        app: riskoptimizer-postgres
spec:
    selector:
        app: riskoptimizer-postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
    type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: riskoptimizer-ingress
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/rate-limit: '100'
        nginx.ingress.kubernetes.io/rate-limit-window: '1m'
spec:
    tls:
        - hosts:
              - api.riskoptimizer.com
          secretName: riskoptimizer-tls
    rules:
        - host: api.riskoptimizer.com
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: riskoptimizer-api-service
                            port:
                                number: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: riskoptimizer-logs-pvc
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: riskoptimizer-redis-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: riskoptimizer-api-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: riskoptimizer-api
    minReplicas: 3
    maxReplicas: 10
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 70
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: riskoptimizer-worker-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: riskoptimizer-worker
    minReplicas: 4
    maxReplicas: 20
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 80
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: 85
